### ISSUE TITLE
pathogen barcodes for Influenza B

### ISSUE THREAD

**Issue by hjp718** [andersen-lab/Freyja-barcodes#2]
Hello,

I'm getting a lot of help with wastewater analysis using Freyja.

I would like to know if you have any plans to upload pathogen barcodes for Influenza B(victoria and yamagata).

or is there a way to analyze Inf B in wastewater using Freyja without pathogen barcodes?

**Comment by joshuailevy** [comment]
Hi @hjp718, 

That's great. We do plan to release barcodes for B/Victoria sometime in the coming few weeks. No plans for B/Yamagata at the moment, since it hasn't been detected in many years now. 

For sure, it depends on what you want to do - as a first pass you'll probably want to just see if any reads align to a Inf B reference (ideally using Inf A references as well during the mapping/alignment step). Some references here: https://github.com/nextstrain/seasonal-flu/tree/master/config/vic

**Comment by cimendes** [comment]
Hey @joshuailevy! I just noticed that the [FLU-B-VIC](https://github.com/andersen-lab/Freyja-barcodes/tree/main/FLU-B-VIC) folder was created but no files were pushed. Was this a mistake? Do you have plans to release these barcodes soon? Thank you!

**Comment by joshuailevy** [comment]
Barcodes should now be available! Thanks @gp201 for the fix!
